printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: none
bracketSpacing: true
arrowParens: always
plugins:
  - prettier-plugin-glsl
overrides:
  - files:
      - "*.frag"
    options:
      parser: glsl-parser
